### ISSUE TITLE
Location-based scheduling is broken

### ISSUE THREAD

**Issue by QkeleQ10** [Armin2208/Windows-Auto-Night-Mode#102]
Location-based scheduling is currently half broken. The offset is never respected and when you keep the app unopened, it doesn't update the sunset and sunrise times (every day the time should change a little, but when you don't open the app it stays the same until you open it again)

**Comment by Armin2208** [comment]
one of the mentioned issues was fixed in https://github.com/Armin2208/Windows-Auto-Night-Mode/commit/9e2869b500a6297882465cbe392b61a0dc92e1da
