### ISSUE TITLE
Jump List doesn't follow set language

### ISSUE THREAD

**Issue by meierlukas** [Armin2208/Windows-Auto-Night-Mode#138]
When changing the language in settings and restarting the app, the language of the entries in the Jump List doesn't change. Restarting the system won't fix it also.

**Comment by Spiritreader** [comment]
Thanks for reporting! We're internally aware of this issue but haven't gotten around to fixing it yet.

**Comment by Armin2208** [comment]
fixed in 3.0.1 ✅
not fixed in version X ❌

**Comment by Spiritreader** [comment]
ported to version X ✅
459f2cb
