### ISSUE TITLE
Please allow selcting Minutes

### ISSUE THREAD

**Issue by CryptKid** [Armin2208/Windows-Auto-Night-Mode#14]
Please add selection fields for Minuts and not only for hours

**Comment by Armin2208** [comment]
Hello!

This feature was introduced in Auto Dark Mode Version 2.1.

[Click here to download the newest version of Auto Dark Mode!](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases)

**Comment by CryptKid** [comment]
I guess, you forgot to close this issue
