### ISSUE TITLE
Latest version not on Winget

### ISSUE THREAD

**Issue by tails618** [Armin2208/Windows-Auto-Night-Mode#140]
I just tried to install this via winget, by running `winget install "Auto Dark Mode"`. Upon opening, I was informed that I was on version 2.x (I don't remember exactly what) and the latest version, on GitHub, was 3.0.

(I haven't tried to put anything on winget, so I don't know if it's unnecessarily complicated or anything. If it's annoying to update what's on winget, that's fine.)

**Comment by Armin2208** [comment]
it's up now!
