### ISSUE TITLE
Feature request: Make taskbar optional

### ISSUE THREAD

**Issue by jportoles** [Armin2208/Windows-Auto-Night-Mode#144]
Would it be possible to make changes to the taskbar optional? I'd like to be able to keep the taskbar always dark regardless whether the system theme is light or dark. This could be done with simple checkbox under settings for example. Thanks!

**Comment by Armin2208** [comment]
Just navigate to Apps and set System to always dark.
Taskbar, Action-Center and Startmenu will be dark, but your Apps will be still in light. It's not possible to control the taskbar seperated from the Startmenu.
