### ISSUE TITLE
The WORDS of windows setting page would be black.

### ISSUE THREAD

**Issue by ForestL18** [Armin2208/Windows-Auto-Night-Mode#150]
When the Windows-Auto-Night-Mode 3.0 automatically switch to dark,the WORDS of windows setting page would be black,too!
 I use the version 2004 now and I have try it several times, but the bug still exists.Hope you can resolve it and help me.Thanks.

**Comment by Armin2208** [comment]
This is a Windows bug, can't be fixed with Auto Dark Mode. I'm sorry!

**Comment by ForestL18** [comment]
You mean the situation will happen when I switch the color mode manually,right?

**Comment by Armin2208** [comment]
this is because it manually refreshes after you press back :D

if you have the black text in settings, you just need to click on a category fand then press back. it's not black anymore.
