### ISSUE TITLE
Please keep release file names and types consistent if possible

### ISSUE THREAD

**Issue by bradenhilton** [Armin2208/Windows-Auto-Night-Mode#156]
I (along with others) have been trying to maintain a package for this app on [scoop](https://scoop.sh/) at https://github.com/TheRandomLabs/scoop-nonportable/blob/master/bucket/auto-dark-mode-np.json. scoop can utilise an autoupdate feature by checking the GitHub releases page and matching a URL template.

The update to 3.0 brought with it a change to the file name (to include the major version number v3) and a change in the file type (from .exe to .zip), this change broke installations of the package and had to be fixed manually. The update to 3.0.1 has again brought a change to the file name (to include the full version number with underscores) and has switched back to a .exe file type, this change has again broken the installation of the package as it tries to download a file that does not exist.

To be clear, I think these changes are great, but if a new update were to go back to a file name of "AutoDarkMode_Setup", or back to a .zip, this would likely break again and require manual intervention.

I'm no scoop expert, but I believe it checks the GitHub release version (e.g. 3.0.1), from which several variables become available to use within the URL, such as $majorVersion (3) and $underscoreVersion (3_0_1).

If you would like more info, please look at https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#version-variables

If possible, please match the release version number with the number used in the file name (e.g. release 4.0 and "AutoDarkMode_v4_0_Setup.exe").

Also, if you would like to add scoop to the Installation section of the README, I would be more than happy to open a PR with the necessary information.

**Comment by Armin2208** [comment]
AutoDarkMode_3_0_2_Setup sounds great. Will maintain this in future.

Zip was an idea to avoid smartscreen. But funny thing: Microsoft manually allows Auto Dark Mode setups in Defender whitelist, because of winget releases. This is why I again removed the zip :D

Sorry guys. We are sticking with exe now. haha.

**Comment by bradenhilton** [comment]
Fantastic, thank you.

I'll close this and update the manfiest now, I'll open a README PR soon regarding scoop installation.

**Comment by bradenhilton** [comment]
Apologies, I have only just seen https://github.com/Armin2208/Windows-Auto-Night-Mode/pull/146. Please disregard my previous comment.
