### ISSUE TITLE
TimZone

### ISSUE THREAD

**Issue by gehtnicht** [Armin2208/Windows-Auto-Night-Mode#16]
AutoNight with Location Service works well but don't use the correct Time Zone. 
e.g. Europe actual it is Winter time the Autonight Mode set to 9:00 am and 6:00 pm but it must be 8:00 am between 5:00 pm. So I guess the time zone will not corectly use.
Windows 1903

**Comment by Armin2208** [comment]
Auto-Night-Mode uses only hours. So I round up the time. If the sun rises at 8:20am the app sets the time to 9am.

**Comment by Armin2208** [comment]
Hello!

Thanks for giving Feedback for Auto Dark Mode. A new Version is out now and should fix your issue. Please try it out and tell me about your experience! 

[Click here to download the newest version of Auto Dark Mode!](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases)
