### ISSUE TITLE
Selected Windows Themes are Not Applied When Manually Changing Mode from Jumplist

### ISSUE THREAD

**Issue by AndrewGaspar** [Armin2208/Windows-Auto-Night-Mode#160]
If you use the jump-list to select "Dark theme" or "Light theme", the selected "Windows Theme" in the "Wallpaper/Theme" menu is not applied. It only applies when automatically switching.

**Comment by Armin2208** [comment]
Which version of Auto Dark Mode do you use?

**Comment by AndrewGaspar** [comment]
![image](https://user-images.githubusercontent.com/2292643/91670318-8cd82600-ead9-11ea-80a6-6aa43e6a524d.png)

**Comment by AndrewGaspar** [comment]
Hm... it seems to be working now. I don't know what changed.

**Comment by AndrewGaspar** [comment]
Sorry for the disruption.

**Comment by Armin2208** [comment]
OK thankfully
