### ISSUE TITLE
Windows 10 Settings app: Captions under menu items invisible after switching dark/light

### ISSUE THREAD

**Issue by welby12** [Armin2208/Windows-Auto-Night-Mode#176]
This has been a reoccurring issue for me. Very often, when the app does it's thing and switches from dark/light, the captions under these Settings items turn invisible. If I click any item, go back, it will appear normal again. I have seen it do this on both dark mode and light mode. 
![Screenshot 2020-11-02 225651](https://user-images.githubusercontent.com/13987200/97957067-14067c00-1d5f-11eb-8ea6-709c5968deb6.png)

**Comment by emberaholdon** [comment]
I have this too but only on my 20H2, 2004 is working fine.

**Comment by welby12** [comment]
I'm on 20H2 also. Not sure when it began, but that seems like a start!!

**Comment by Armin2208** [comment]
It's a Windows 10 issue since ever.
Auto Dark Mode can't fix it, only Microsoft. Sorry.
