### ISSUE TITLE
Please add 4 different wallpapers/themes along the day.

### ISSUE THREAD

**Issue by davidhdez** [Armin2208/Windows-Auto-Night-Mode#181]
Would be amazing if it an option to set 4 different wallpapers along the day, for early morning, afternoon, evening, and night.

**Comment by emberaholdon** [comment]
> Would be amazing if it an option to set 4 different wallpapers along the day, for early morning, afternoon, evening, and night.

It's far too few IMHO. I use WinDynamicDesktop with the Mojave wallpaper pack and it consists of 16 images.

**Comment by davidhdez** [comment]
I didn't know it, thank you so much, was exactly for something like this macOS style feature that I wanted. I will install it.

**Comment by emberaholdon** [comment]
> Btw, do you think is possible to use both applications at the same time? one for change the theme only dark/light and the other for the background. thank you.

I’m using them exaclty like this. Just turn off wallpaper/theme change in Auto-Dark-Mode and it should be fine.
