### ISSUE TITLE
Now Office changes automatically theme

### ISSUE THREAD

**Issue by tiziodcaio** [Armin2208/Windows-Auto-Night-Mode#189]
I leave a screenshot with build number 
![immagine](https://user-images.githubusercontent.com/61084118/102215024-68ae2280-3ed9-11eb-837f-b6e70385fd51.png)

**Comment by Armin2208** [comment]
yes

**Comment by emberaholdon** [comment]
> yes

Well, not exactly. When Auto-Night-Mode changes to dark theme it sets Office to "black" instead of leaving it on "use system setting".
