### ISSUE TITLE
Edge is using the wrong theme

### ISSUE THREAD

**Issue by 19lmyers** [Armin2208/Windows-Auto-Night-Mode#19]
Windows 10 1903, app version 2.0

The app works as expected, but Edge is consistently being set to the opposite of what it should be. When the system is light, it is dark, and when the system is dark, it is light.

This continues to be the case even after restarting Edge multiple times.

**Comment by 19lmyers** [comment]
The issue resolved itself after waiting a few minutes, for some reason.

**Comment by 19lmyers** [comment]
Sorry, I confused myself after setting the option for Edge to "Always light" and thinking it was working. _(Because it was dark after changing that setting!)_

**Comment by Armin2208** [comment]
I fixed that in a commit of 7th february. I should invest some Hours work and finally release Version 2.1 with that fix.

Thank you!

**Comment by Armin2208** [comment]
Hello!

Thanks for giving Feedback for Auto Dark Mode. A new Version is out now and should fix your issue. Please try it out and tell me about your experience! 

[Click here to download the newest version of Auto Dark Mode!](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases)

**Comment by Armin2208** [comment]
Hello!

Thanks for giving Feedback for Auto Dark Mode. A new Version is out now and should fix your issue. Please try it out and tell me about your experience! 

[Click here to download the newest version of Auto Dark Mode!](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases)

**Comment by 19lmyers** [comment]
That fixed it, thanks!
