### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tiziodcaio** [Armin2208/Windows-Auto-Night-Mode#190]
![immagine](https://user-images.githubusercontent.com/61084118/102215212-b165db80-3ed9-11eb-9a7c-d0c7f24b55aa.png)
When I click on custom position appears this error... I can't use the application!

**Comment by Armin2208** [comment]
which custom position?

**Comment by tiziodcaio** [comment]
Udine Italy

**Comment by Armin2208** [comment]
thanks for the language, but I don't understand "When I click on custom position appears this error" :D What is custom position?

**Comment by tiziodcaio** [comment]
No, sorry, when i click changing the auto dark to position...

**Comment by Armin2208** [comment]
Okay. Do you use 12 or 24 hour clock?

**Comment by tiziodcaio** [comment]
24 H

**Comment by whyjxz14** [comment]
![image](https://user-images.githubusercontent.com/6323818/103471890-09c42680-4d7e-11eb-90f1-49b4a442f3c3.png)
it seems not a 12/24 h problem, and it also has no relation between custom positions. It just appears when you apply the settings.
The first time I open the app it works ok. The next time it keeps report and crash. It also happens in English mode

**Comment by tiziodcaio** [comment]
So... it's solved?

**Comment by whyjxz14** [comment]
> 所以...解决了吗？

youcan download the beta version on https://t.me/autodarkmode

do not have this problem

**Comment by tiziodcaio** [comment]
> > 所以...解决了吗？
> 
> youcan download the beta version on https://t.me/autodarkmode
> 
> do not have this problem

Ok thanks
