### ISSUE TITLE
[Feature request] Support Windows 10 light theme in taskbar

### ISSUE THREAD

**Issue by jordi-7** [Armin2208/Windows-Auto-Night-Mode#2]
Windows 10 introduced a system light theme that tints the taskbar in the latest insider previews, which will come to the stable version in the first half of 2019.

https://blogs.windows.com/windowsexperience/2018/11/14/announcing-windows-10-insider-preview-build-18282/#BB7iwCs7YmIQzLBe.97

With that, the theme can be changed in two ways separatelly, apps and system, inside the registry:
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize
-AppsUseLightTheme
-SystemUsesLightTheme (this is the new one introducen in the latest previews, changes the taskbar)

**Comment by Armin2208** [comment]
Thank you for providing me the new RegKey. This feature will definitely arrive, it is on my to-do-list. But it has atm low priority, because the release of 1903 will be in 4 months.

**Comment by jordi-7** [comment]
Awesome. I understand it's not a priority, it's logical. Anyway, whenever you implement it, I'll be able to test since I am on the insider channel. 
Thanks!

**Comment by jordi-7** [comment]
I've been trying it and works flawlessly! No issuer for now, all working as expected and very easy to set up.

**Comment by Armin2208** [comment]
Version 2.0 is now out of beta. It includes this feature and more enhancements. Thank you for your feedback.
