### ISSUE TITLE
VERY Delayed 

### ISSUE THREAD

**Issue by ghost** [Armin2208/Windows-Auto-Night-Mode#20]
ANM applies the theme but after so much time, like 10-20 minutes. I tried reinstalling it several times. Nothing worked. Sometimes, it doesn't even work at all. Or, if I'm in an app like MyTube, it gets really glitchy. The only workaround right now is starting the application itself, as that immediately sets in/out dark mode. I hope this can be fixed, since the program is really wonderful, but it for some reason takes so long to work.

**Comment by VincentJoshuaET** [comment]
Same issue.

**Comment by Armin2208** [comment]
Do you use the program on a Desktop PC or on a battery powered device like Notebook or Tablet?

**Comment by Armin2208** [comment]
Hello!

Thanks for giving Feedback for Auto Dark Mode. A new Version is out now and should fix your issue. Please try it out and give me some Feedback!

[Click here to download the newest version of Auto Dark Mode!](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases)
