### ISSUE TITLE
Cannot select office theme

### ISSUE THREAD

**Issue by Namu-Lee** [Armin2208/Windows-Auto-Night-Mode#200]
I can't select the theme option for office. The dropdown menu shows well, but selection doesn't respond.
Selection with keyboard input(Up, Down key) works, but theme change still not works.

I'm using Office 365 Enterprise with my student account.

Thanks.

**Comment by otabekan** [comment]
@Namu-Lee are you using Windows Themes to switch modes?

**Comment by Armin2208** [comment]
Auto Dark Mode checks if the Registry Entry for Office exists (if it's installed) and if yes it selects the dropdown and if no it refuses to enable this.
Seems like you don't have a Office profile in your Registry.
But you are using Office 365. Microsoft integratet system based theme switching now on their own there.

**Comment by Namu-Lee** [comment]
I found office theme settings and changed it. Works well. Thanks.
