### ISSUE TITLE
Unreadable text in Windows Settings

### ISSUE THREAD

**Issue by ncodee** [Armin2208/Windows-Auto-Night-Mode#210]
Hi, not sure if reported already, but when the theme switches from Light to Dark, the text is pitch black which makes it unreadable on Windows Settings.

**Comment by zhenjie1999** [comment]
mine is setting app all description is missing but will back to normal go forward and backward again

**Comment by Armin2208** [comment]
reportet, but not fixable, because this is a windows bug. maybe fixed in 11.
