### ISSUE TITLE
According Browser Extension

### ISSUE THREAD

**Issue by simonferndriger** [Armin2208/Windows-Auto-Night-Mode#211]
Do you have or know a (Chrome) browser extension, that uses the Windows dark/light mode settings to either convert pages into dark/light mode accordingly?

Youtube already does it by its own.

**Comment by emberaholdon** [comment]
> Do you have or know a (Chrome) browser extension, that uses the Windows dark/light mode settings

Use Dark Reader, you can find the download link in the about page of the app. Works for Edge too.

**Comment by simonferndriger** [comment]
Awesome, thank you!
