### ISSUE TITLE
[Feature request] Add Auto Night Mode in VS Cond and VS Studio 

### ISSUE THREAD

**Issue by feradr** [Armin2208/Windows-Auto-Night-Mode#215]
It would also be nice to change the themes to Visual Studio Code and Visual Studio IDE.

Alias thank you for making available to us the
Windows-Auto-Night-Mode.

**Comment by m3rc1ful** [comment]
@feradr you can config VS Code to follow OS color theme, that way it will change whenever your OS theme changes.
Look for "auto detect color theme" under settings.

**Comment by Armin2208** [comment]
have a look at:
https://github.com/Armin2208/Windows-Auto-Night-Mode/wiki/Apps-with-Auto-Dark-Mode-support
