### ISSUE TITLE
Not sure if this is an issue or not, but sometimes the quick shortcuts don't appear in the context menu

### ISSUE THREAD

**Issue by mukundshah** [Armin2208/Windows-Auto-Night-Mode#216]
![image](https://user-images.githubusercontent.com/39938037/111978640-3f321200-8b2c-11eb-9e40-d7d17834359c.png)

Windows 10 20H2 19042.867

**Comment by Armin2208** [comment]
thanks

**Comment by mukundshah** [comment]
This wasn't the issue at all. It happened because I had turned off a setting.
![image](https://user-images.githubusercontent.com/39938037/113539796-4feb8900-95fe-11eb-9f74-8e124567073d.png)
However, I had to re-install after enabling this setting, to get it working.

Thank you and sorry.

**Comment by Armin2208** [comment]
> This wasn't the issue at all. It happened because I had turned off a setting.
> ![image](https://user-images.githubusercontent.com/39938037/113539796-4feb8900-95fe-11eb-9f74-8e124567073d.png)
> However, I had to re-install after enabling this setting, to get it working.
> 
> Thank you and sorry.

okay that's interesting. thanks for the notice!
