### ISSUE TITLE
Feature request: Desktop color settings

### ISSUE THREAD

**Issue by jorismak** [Armin2208/Windows-Auto-Night-Mode#221]
Currently, the wallpaper-settings only allow for setting an image.

I only use the 'solid color' option, and would've hoped I could change that when changing light/dark mode.

**Comment by Armin2208** [comment]
Can you do this with Windows theme switching?

**Comment by jorismak** [comment]
Oh, I must have missed that option the first time. I thought it was only possible to alter desktop-wallpaper.

Setting it to full 'windows theme' mode would allow me to configure two themes with different colors I guess. Thanks!

**Comment by Armin2208** [comment]
did you suceed that?
