### ISSUE TITLE
[BUG]It is impossible to switch to dark mode after 24:00.

### ISSUE THREAD

**Issue by DEabcdp** [Armin2208/Windows-Auto-Night-Mode#226]
It is impossible to switch to dark mode after 24:00. For example, I want light mode from 6:00-2:00 (the next day), which cannot be done.

**Comment by Spiritreader** [comment]
Could you be a bit more specific please? 
And could you post screenshots of what you've configured and why it isn't working? 

You should be able to type in any number you want for start and end times.

**Comment by DEabcdp** [comment]
When I click "Apply" in Figure 1, the program automatically changes "2:00" to "17:00", as shown in Figure 2. That is, it cannot be set to the next day.
![1](https://user-images.githubusercontent.com/62452364/118637800-c4723400-b808-11eb-9a34-32e2761e15b5.png)
![2](https://user-images.githubusercontent.com/62452364/118637812-c76d2480-b808-11eb-8199-04e8906cbd31.png)



> Could you be a bit more specific please?
> And could you post screenshots of what you've configured and why it isn't working?
> 
> You should be able to type in any number you want for start and end times.

**Comment by Spiritreader** [comment]
issue fixed for next beta release, thanks!
