### ISSUE TITLE
Problem with Russian translation

### ISSUE THREAD

**Issue by SeregaKR** [Armin2208/Windows-Auto-Night-Mode#227]
Versions tested: 3.1 stable and Beta4.
In russian translation the option "Use grayscale color filter (sends Win + Ctrl + G)" is not fully visible - because the text is too long. Can you increase the window width or add the word wrap option for this checkbox?
![изображение](https://user-images.githubusercontent.com/1452103/118816665-b2e56680-b8b2-11eb-8825-686e802cbc52.png)

For Beta4 the translation is not complete: the button caption "Set" is not translated (see Time tab)

**Comment by Armin2208** [comment]
thanks! will see

**Comment by stanislav-suslov** [comment]
I also created small fix at #232.

**Comment by Armin2208** [comment]
merged
