### ISSUE TITLE
Choose a wallpaper for light and other for dark mode

### ISSUE THREAD

**Issue by ycanales** [Armin2208/Windows-Auto-Night-Mode#23]

**Comment by Armin2208** [comment]
Planned feature.

**Comment by sandeepb1** [comment]
+1 Came here to request this. It would be a great addition

**Comment by Armin2208** [comment]
Hello!

Thanks for giving Feedback for Auto Dark Mode. A new Version is out now including your suggestion. Please try it out and tell me about your experience!

[Click here to download the newest version of Auto Dark Mode!](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases/tag/2.2)
