### ISSUE TITLE
About setting window

### ISSUE THREAD

**Issue by matsuda0707** [Armin2208/Windows-Auto-Night-Mode#233]
When setting Windows-Auto-Night-Mode, it is displayed as half transparent window, and it is not easy to read the menu when the backgroud wallpaper is light or white color.
So could you consider tochange setting window to opaque?

![Screenshot_1](https://user-images.githubusercontent.com/22485788/123192321-9eae0e00-d4dd-11eb-847b-4bb1282a3142.jpg)

**Comment by Armin2208** [comment]
are you using it on a virtual machine?

**Comment by matsuda0707** [comment]
Yes. I use Vmware player.
I remember that this occur frequently on VM.

**Comment by Armin2208** [comment]
yep, this occurs only and often von VMWare.
This was once fixed, but now it's again here. Fuck! :D 
I will not fix this, probably I will switch to WinUI3 end of the year, so the UI will be re-coded anyways.
