### ISSUE TITLE
Switch to MIT licensed sunrise calculator implementation

### ISSUE THREAD

**Issue by jwfxpr** [Armin2208/Windows-Auto-Night-Mode#236]
As discussed at microsoft/PowerToys#1331, I'm the author of [SunriseCalculator](https://github.com/jwfxpr/SunriseCalculator), an MIT licensed implementation of the sunrise calculator you're using here. My implementation is more _C#-ish_ than your current one, which I think returns an `int[2]` of... minutes? for the rise and set times, whereas I return two `DateTime`s and an enum that explicitly reports whether sunrise/set occurs on that day (for locations near or outside the Arctic circles).

Do you want help with replacing and refactoring around the GPL3 code? I'm happy to fork and create a draft PR, if that's helpful.

**Comment by jwfxpr** [comment]
As a side note, I tried testing my calculator against the output of `SunDate.cs` for a sanity check, and discovered that SunDate actually produces nonsense values with surprising regularity, sometimes reporting sunrise or sunset values that are more than a _day_ incorrect. This can lead to these lines [here](https://github.com/Armin2208/Windows-Auto-Night-Mode/blob/1c365b65fd786081a3774254243346851d1b80e1/AutoDarkModeSvc/Handlers/LocationHandler.cs#L19-L20):

``` C#
            configBuilder.LocationData.Sunrise = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, sun[0] / 60, sun[0] - (sun[0] / 60) * 60, 0);
            configBuilder.LocationData.Sunset = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, sun[1] / 60, sun[1] - (sun[1] / 60) * 60, 0);
```
raising exceptions from an `hours` value > 23. If you've had trouble tracking down the source of `ArgumentOutOfRange` exceptions thrown by `DateTime`, this may be the cause of the problem. Interestingly<sup>†</sup>, the issues with SunDate's results aren't limited to extreme latitudes, which one might expect. It could be because the SunDate implementation does a _huge_ amount of unneccessary conversion back and forth between degrees and radians, resulting in an accumulation of double arithmetic errors which, when handling a lot of tiny values, can cause significant variation in results. But that's just a guess. 🤷‍♂️

**Comment by jwfxpr** [comment]
I had time today and the change was so trivial, I just went ahead and did the thing in PR #237. 👍

**Comment by Spiritreader** [comment]
> As a side note, I tried testing my calculator against the output of `SunDate.cs` for a sanity check, and discovered that SunDate actually produces nonsense values with surprising regularity, sometimes reporting sunrise or sunset values that are more than a _day_ incorrect. This can lead to these lines [here](https://github.com/Armin2208/Windows-Auto-Night-Mode/blob/1c365b65fd786081a3774254243346851d1b80e1/AutoDarkModeSvc/Handlers/LocationHandler.cs#L19-L20):
> 
> ```cs
>             configBuilder.LocationData.Sunrise = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, sun[0] / 60, sun[0] - (sun[0] / 60) * 60, 0);
>             configBuilder.LocationData.Sunset = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, sun[1] / 60, sun[1] - (sun[1] / 60) * 60, 0);
> ```
> 
> raising exceptions from an `hours` value > 23. If you've had trouble tracking down the source of `ArgumentOutOfRange` exceptions thrown by `DateTime`, this may be the cause of the problem. Interestingly†, the issues with SunDate's results aren't limited to extreme latitudes, which one might expect. It could be because the SunDate implementation does a _huge_ amount of unneccessary conversion back and forth between degrees and radians, resulting in an accumulation of double arithmetic errors which, when handling a lot of tiny values, can cause significant variation in results. But that's just a guess. 🤷‍♂️

That is a very nice find. 
When I adapted the sunrise calculations to work with the new Version X, I didn't look at the stability of the sunrise calculation library, and I never noticed this exception in anyof my tests, because where I live, Sunset is always before 23:00.

Help is always welcome. I've went ahead and given my go for PR #237, now only @Armin2208's approval is missing, which I think we will have very shortly, as your work looks very diligently done.

Thank you!
