### ISSUE TITLE
Use Edge Different Theme Settings for Chrome Instead

### ISSUE THREAD

**Issue by Ninja73737** [Armin2208/Windows-Auto-Night-Mode#25]
Hi! I use chrome instead of edge, and it'd be great if I could use this application to single that browser out instead of edge.

Regardless of whether or not you have time to add this feature, thank you for your work on this application, I've been waiting for something like this after getting used to Nightowl on my mac.

**Comment by Armin2208** [comment]
Hello,

both Firefox and Chrome (ver. 75) now supports auto dark mode. You need to reset both to the standard theme, to make use of it. Have fun :)
