### ISSUE TITLE
Icon in notification area

### ISSUE THREAD

**Issue by mariniric** [Armin2208/Windows-Auto-Night-Mode#26]
Thank you very much for this application.
It would be very nice to have an icon in the notification area to fastly switch between light and dark theme
![immagine](https://user-images.githubusercontent.com/50889964/58132999-06207200-7c23-11e9-9467-8f630af02a7a.png)

**Comment by Armin2208** [comment]
Thanks for the request. I will check this.

**Comment by Armin2208** [comment]
Thanks for your request. Did you tried the jump list of auto dark mode?

**Comment by mariniric** [comment]
Yes, I tried but I think it would be more useful having just a small icon in the notification area instead of opening start or pinning it in the app bar

**Comment by Spiritreader** [comment]
added in 9ab9da1

**Comment by emberaholdon** [comment]
> Thank you very much for this application.
> It would be very nice to have an icon in the notification area to fastly switch between light and dark theme
> ![immagine](https://user-images.githubusercontent.com/50889964/58132999-06207200-7c23-11e9-9467-8f630af02a7a.png)

Oh God, please no! There is already enught junk in the systray, no need for another icon there (originally this was a notification area, placing permanent icons there is not even recommended. If there is going to be a systray icon, please at least make it optional.

**Comment by Armin2208** [comment]
tray is the perfect place to see which applications are running currently and maybe giving the users access to some handy features.

**Comment by emberaholdon** [comment]
> tray is the perfect place to see which applications are running currently and maybe giving the users access to some handy features.

Sorry, but no. The taskbar is the place to show running apps, the “tray” was never meant to be the junkyard like it is today. It is there to show notifications, and it’s quite obsolete now becuse of the Action Center.

See: https://docs.microsoft.com/en-us/windows/win32/uxguide/winenv-notification

**Comment by Rex501st** [comment]
> > tray is the perfect place to see which applications are running currently and maybe giving the users access to some handy features.
> 
> Sorry, but no. The taskbar is the place to show running apps, the “tray” was never meant to be the junkyard like it is today. It is there to show notifications, and it’s quite obsolete now becuse of the Action Center.
> 
> See: https://docs.microsoft.com/en-us/windows/win32/uxguide/winenv-notification
> 
> “Is the icon primarily to launch a program or access its features or settings quickly? If so, use the Start menu to launch programs instead. The notification area isn't intended for quick program or command access.”

Should read what you post before acting like a jackass.

![image](https://user-images.githubusercontent.com/25782090/113782010-85c46680-96ff-11eb-801b-1ca8b0373a87.png)

**Comment by emberaholdon** [comment]
> ![image](https://user-images.githubusercontent.com/25782090/113782219-ddfb6880-96ff-11eb-8744-740a3c6ba5d3.png)

This is far outdated, it's a Win7 screenshot for fucks sake. Action Center has its own UI now but even back then it was only displaying the icon WHILE it was performing an action. If you like clutter, fine, have all the icons in the world next to the clock but I like my stuff clean. Jackass.

**Comment by daniel-liuzzi** [comment]
> 
> 
> added in [9ab9da1](https://github.com/Armin2208/Windows-Auto-Night-Mode/commit/9ab9da11876af209303d600c95e02375a420bd59)

Sorry to necropost, but is there anything special needed for the tray icon? I'm on the latest release (3.0.1) and the notification icon is nowhere to be found. I installed the app manually by running the setup .exe file, and also via scoop (both portable and non-portable) to no avail. Everything else seems to work OK.

**Comment by Armin2208** [comment]
Notification Icon is not in stable yet

**Comment by daniel-liuzzi** [comment]
Oh, that explains it. Thanks for the response!

**Comment by Rex501st** [comment]
> > ![image](https://user-images.githubusercontent.com/25782090/113782219-ddfb6880-96ff-11eb-8744-740a3c6ba5d3.png)
> 
> This is far outdated, it's a Win7 screenshot for fucks sake. Action Center has its own UI now but even back then it was only displaying the icon WHILE it was performing an action. If you like clutter, fine, have all the icons in the world next to the clock but I like my stuff clean. Jackass.
> 
> Also, who the fuck wants to change between themes all the time so that it needs a permanent icon/switch? The whole point of this app is that it does shit automatically.

It's as if you can hide the icon, in the settings app, to prevent it from ever showing up, something that has been a feature since XP! I swear you are on the spectrum.

**Comment by Spiritreader** [comment]
Seeing as there's no real productive conversation on this topic anymore:

Tray icon will be a feature in version X, following the behavior of many background running applications to date that are to be interacted with. 

Thanks for everyone's input, and please remember to be friendly and reasonably to each other.

**Comment by Spiritreader** [comment]
Final behavior for version X

fe5b112
This option is now **enabled by default**, but can be disabled by editing a config file tunable.

There will be a `ShowTrayIcon` setting available for those who don't want it.
There is STILL a background process running when disabling this. It ist just no longer visible to the user.
Disabling the tray icon means there is no way to exit the service other than task manager, which is considered an unclean shutdown. A future release will allow to stop the service using CMD via NetMQ.

Use it at your own discretion, for now and ever.

```
Tunable:
  BatterySliderDefaultValue: 25
  DisableEnergySaverOnThemeSwitch: false
  UseLogonTask: false
  Debug: true
  ShowTrayIcon: true // set to false if desired
```
