### ISSUE TITLE
Does not update Firefox content

### ISSUE THREAD

**Issue by fenhl** [Armin2208/Windows-Auto-Night-Mode#27]
**Describe the bug**
Firefox 67 has a feature where websites can be styled differently in dark mode. Toggling dark mode using this program does not update any open pages.

**To Reproduce**
1. Start in light mode
1. Open <https://bugzilla.mozilla.org/> in Firefox 67
2. Run `path\to\AutoDarkMode.exe /dark` in a PowerShell
3. Bugzilla is still in light mode

**Expected behavior**
Bugzilla should immediately update to be in dark mode.

**Environment:**
 - OS Version: Windows 1803
 - Night-Mode Version 2.1.1
 - Has user admin rights? Yes
 - which antivirus software you use? Windows Defender
 - what language is your Windows set to? English

**Additional context**
This does work as expected when using the toggle in the Settings app, so there's a difference in beavior here.

**Comment by Armin2208** [comment]
This issue was fixed by Mozilla. It works without problems now.

**Comment by pjpscriv** [comment]
I was having a similar issue and it turns out the solution was to update the **Web Appearance** setting from `Firefox theme` to `System theme`.

![image](https://user-images.githubusercontent.com/16329923/171304599-c67531bb-45f5-49df-ab02-f5a0c350a3eb.png)
