### ISSUE TITLE
Dragging the window around lags

### ISSUE THREAD

**Issue by 19lmyers** [Armin2208/Windows-Auto-Night-Mode#28]
Since version 2.2, dragging the app window has a noticeable lag to it.

**Comment by Armin2208** [comment]
This is an issue with some graphic driver in Windows 1903.
I have the same issue on my PC with Nvidia drivers, but not on my Notebook with Intel HD driver.
You can compare that to Windows + dot emoji panel: try to drag this and you see the same lag.
For Microsoft it's a known issue and we wait for a fix.

**Comment by TimmSkiller** [comment]
For me, it's not lagging, but like dragging VERY SLOWLY. Its like ghosting.

**Comment by Armin2208** [comment]
Will be fixed in next update

**Comment by neFAST** [comment]
It is still there in v2.3

**Comment by moseoridev** [comment]
Yeah, It is still laggy when grab window.

**Comment by 19lmyers** [comment]
I'm still seeing this too,

**Comment by neFAST** [comment]
Fixed with latest nightly zip
