### ISSUE TITLE
[Feature request] Use local sunrise/sunset times to change themes

### ISSUE THREAD

**Issue by fenrisswolf** [Armin2208/Windows-Auto-Night-Mode#3]
This might be something to think about a bit down the line, but I'd love it if it would eventually change the theme based on the sunrise and sunset times.

I do think this is a feature that should have been baked into the OS, but thanks for making this app and taking care of it!

**Comment by Armin2208** [comment]
Feature is planned and will come soon(tm).

**Comment by jordi-7** [comment]
Works very well!

**Comment by Armin2208** [comment]
Version 2.0 is now out of beta. It includes this feature and more enhancements. Thank you for your feedback.
