### ISSUE TITLE
Taskbar won't change to white when switching from dark to light until reload

### ISSUE THREAD

**Issue by TYHuff** [Armin2208/Windows-Auto-Night-Mode#30]
When switching between themes, sometimes text and icons usually stay the same color until you reload. Normally this isn't an issue but there isn't a reliable and easy way to reload the taskbar.

**Comment by Armin2208** [comment]
Hello.

It does switch. But only after closing the main window for the first time, because when the app saved the config.
Switching the theme from the Taskbar creates a new instance of the app. And this instance doesn't know anything about your custom background until you didn't close the main window.

try that again and tell me if it's working for you.

**Comment by Armin2208** [comment]
Which icons do you mean?

**Comment by matsuda0707** [comment]
The icons in taskbar such as Windows flag, search,cortana, settings, MS store are changed correctly, but the icons in the notification area such as device detach, wifi, sound are not changed! (remains in black at night mode change). They are changed to white when causing the status change of each icons (detach device, change of wifi network, or volume change)

**Comment by Armin2208** [comment]
Weird. They change for me. Has anyone the same experience?

**Comment by matsuda0707** [comment]
The icons in the notification area (sound volume, Wifi, device detach,etc) do NOT change even after scheduled change. The icons in the taskbar (left side) changes on schedule!

**Comment by MercuryXIII** [comment]
I also have this issue.

**Comment by YadominJinta** [comment]
I have the same experience.
When change from light to dark theme, all effect except the status bar stay the same. Only re-login can fix it.

**Comment by Armin2208** [comment]
Do you use some modification like TranslucentTB?

**Comment by YadominJinta** [comment]
> Do you use some modification like TranslucentTB?

No, I didn't use that.

**Comment by YadominJinta** [comment]
Even I switch theme manully, the taskbar won't change.
But when I try to uninstall Auto-Night-Mode and reboot, it turns back to usable.

**Comment by Armin2208** [comment]
Do you guys have the same issue then switching the theme multiple times in windows settings?

**Comment by YadominJinta** [comment]
Now I think it is a bug in Win. Please vote me here.
[Taskbar won't change color when switching color theme](https://aka.ms/AA5k140)

**Comment by YadominJinta** [comment]
Now I discovered it's because the energy saving mode.
Quit energy saving mode can fix it.

**Comment by Armin2208** [comment]
I checked it and you are right. In Battery Safer the theme switch doesn't work. Wow! 

We should report this to Microsoft.

Thank you.

**Comment by Armin2208** [comment]
I've added a message informing about the situation with energy saver with the recommendation to deactivate it:
[Click here to see a screenshot](https://ibb.co/GJhRn1M)

**Comment by Jnss98b** [comment]
My situation is weird. It never fails to change on my laptop, which is in battery saving mode 1/3 of the time but sometimes doesn't for all icons on my desktop PC, which is in performance mode 100% of the time

**Comment by Spiritreader** [comment]
I think this is also related to what I mentioned in #76.

This will hopefully be fixed in v3 where you can set a delay but will need testing.

**Comment by Armin2208** [comment]
Are you guys having this issue and are you using accent color for taskbar?

**Comment by Spiritreader** [comment]
Should be fixed in version 3 and up.
Please see #91 for details.
