### ISSUE TITLE
Use with schedule night light windows?

### ISSUE THREAD

**Issue by mirbaagheri** [Armin2208/Windows-Auto-Night-Mode#31]
Is there any way to use with schedule night light windows(sunset to sunrise)?
That's mean schedule of your app works with schedule night light windows.
![Annotation 2019-05-29 225607](https://user-images.githubusercontent.com/11602249/58581534-03e29700-8265-11e9-86ab-39b71a37e0db.png)

**Comment by Armin2208** [comment]
It's not possible and I don't know why you want this. Windows uses the same sunset and sunrise times as auto dark mode.

**Comment by mirbaagheri** [comment]
I checked `Use Location Service` check box and solved.
Thank you
