### ISSUE TITLE
Auto-night-mode is displayed in acryl window

### ISSUE THREAD

**Issue by matsuda0707** [Armin2208/Windows-Auto-Night-Mode#33]
When run auto-night-mode, the setting windows is displayed in acryl mode(?) and it can not read for setting menus.
In ths case, by mouse hovering on the window, the setting menu become visible!

**Comment by Armin2208** [comment]
Click once out of the window and then back in. Content should be visible.

**Comment by Armin2208** [comment]
Will be fixed in the next update
