### ISSUE TITLE
[Feature request] Switching between 2 file folder in Desktop Background 

### ISSUE THREAD

**Issue by CharleyMorgan** [Armin2208/Windows-Auto-Night-Mode#35]
Most people have a lot of wallpaper, but now Configure Desktop Background only can pick file.

**Comment by callmejay758** [comment]
Yes i agree. I have a bunch of wallpapers that change every hour, however when they change the contrast is usually not right. It'd be nice if it can detect the wallpaper's tone overall and switch based on that, or at least allow me to manually pick light/dark mode for each wallpaper in the folder.

**Comment by Coupz** [comment]
Would love to have this feature too. 👍

**Comment by Armin2208** [comment]
Hey! Check out the new beta release and give me some feedback: [version 2.4 Beta](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases/tag/2.4)

**Comment by Coupz** [comment]
Thank you Armin. Testing the beta right now and will report back.

**Comment by Coupz** [comment]
Until now, it works great. It smoothly switches to dark mode and the background image slideshows for light and dark mode in windows work as expected. Thank you Armin 👍
