### ISSUE TITLE
Windows 10 Start menu shows Auto Dark mode and Auto Night mode listings...

### ISSUE THREAD

**Issue by fenrisswolf** [Armin2208/Windows-Auto-Night-Mode#38]
My current installation shows an Icon for both version 2.0.0.0 (Auto Night Mode) and version 2.2.0.0, Auto Dark Mode.)   Clicking on the icon for the old version launches an update prompt, and the new icon launches the current version.  

Attempting to uninstall just takes me to removing the current version.

**Comment by Armin2208** [comment]
Hello.
Thanks for your issue. Sadly the installation and uninstallation process isn't provided by me, but I only use the Inno Setup Tool.
Normally he should handle that without problems. I also testet it on my machine and the switch from auto night mode to auto dark mode worked.
You need to manually remove the old version, it is located in your app data folder.

**Comment by Armin2208** [comment]
Did you try to uninstall? I tried it now and it removed both versoins.

**Comment by fenrisswolf** [comment]
Uninstall works.   As a side note the new version's (2.3) implementation of location service seems quicker. Thanks for all the hard work!
