### ISSUE TITLE
[BUG] The app makes windows explorer buggy.

### ISSUE THREAD

**Issue by Tom4tot** [Armin2208/Windows-Auto-Night-Mode#4]
**Describe the bug**

**To Reproduce**
1. Make the app change theme
2. the explorer looks weird. See screenshots.

**Expected behavior**
The explorer shouldn't be buggy. I'd suggest your app could reload explorer.exe until MS fixes it.

**Screenshots**
1:  appearance if a windows explorer is already opened: https://i.imgur.com/eYRZeY1.png
2: apperance if I quit the current window and open a new one: https://i.imgur.com/M7b2IWz.png
3: expected appearence, when I reload from task manager explorer.exe: https://i.imgur.com/qEFZVLT.png

**Environment:**
 - OS Version: 1809
 - Night-Mode Versio: 1.0
 - Has user admin rights: no
 - which antivirus software you use: none
 - what language is your Windows set to: english

**Additional context**
-The same happens to me when I directly use the task scheduler to change theme.

**Comment by Armin2208** [comment]
Hello,
thanks for providing me a good bug report!

I can reproduce the bug and I know that it exists. The theme switch from the microsoft settings app works much better than of my app, without restarting the explorer.exe. I think Microsoft uses a own way to refresh the window, which I should try to reconstruct.

I don't want  to simply restart the whole explorer.exe-process, because this can cause some other disadvantages.

**Comment by Tom4tot** [comment]
Hi, thanks for your quick feedback. Looking forward for the next updates then. :)

**Comment by Armin2208** [comment]
Update:
I looked at the log of immserviceSettings.exe, explorer.exe and dwm.exe while changing the theme. So much stuff is going on, it would take hours to analyze that.
Plus I tried to switch the theme in Windows 19H1 Insider-Build. Already in Build 18272 they optimized the way how the explorer handles theme changes and my tool works fine there. The update will probably release in April 2019.

I think it isn't worth the work, when Microsoft already fixed it, or?

**Comment by jordi-7** [comment]
I am running the insider build and I can confirm this is fixed.
IMO, this shouldn't be a priority.

**Comment by Tom4tot** [comment]
I think it isn't worth the work indeed however it's hardly recommendable on 1809 as the result is very frustrating and ugly... Microsoft is so bad...

**Comment by kid1412621** [comment]
same here ... 
![image](https://user-images.githubusercontent.com/26278054/49411994-ea74fc80-f7a5-11e8-814b-7684bdf45ad3.png)

**Comment by Armin2208** [comment]
Update: Windows Settings seems to call something that I can't access. So fix isn't possible atm.

**Comment by Tom4tot** [comment]
Thanks for letting us know!

**Comment by Armin2208** [comment]
While programming the next version of Auto-Night Mode I noticed that my Windows 1809 now switches the theme perfectly. Build: 17763.195.

Can you guys check the behaviour on your machine? Could it be that Microsoft pushed some improvements with a cumulative update. Would be nice!

**Comment by Tom4tot** [comment]
> 
> 
> While programming the next version of Auto-Night Mode I noticed that my Windows 1809 now switches the theme perfectly. Build: 17763.195.
> 
> Can you guys check the behaviour on your machine? Could it be that Microsoft pushed some improvements with a cumulative update. Would be nice!

Yes it works perfectly now! Thanks for the status update. :)
