### ISSUE TITLE
Window Focus Resets When Theme Switch Activates

### ISSUE THREAD

**Issue by OpenRift412** [Armin2208/Windows-Auto-Night-Mode#42]
It is most noticeable when playing a game. I'll be in the middle of a game, when all of a sudden, the game window goes out of focus when the theme changes from light to dark. Is there a way for you to fix this?

**Comment by Armin2208** [comment]
Which version of AutoDarkMode do you use?

**Comment by Armin2208** [comment]
can't reproduce. There's only a small lag while changing the theme. But this can't be fixed, because Windows Explorer takes all the ressources for the theme switch.
