### ISSUE TITLE
[Feature request] Option to use accent color only on night or day 

### ISSUE THREAD

**Issue by dboun** [Armin2208/Windows-Auto-Night-Mode#46]
It would be great if the checkbox to 'use accent color for taskbar' would be removed and be replaced with:

- 'use accent color for taskbar in light mode'
- 'use accent color for taskbar in dark mode'

That's because I like the light white task bar, but I find the black one boring. Someone else might feel the reverse.

Thank you!

**Comment by Armin2208** [comment]
you can't put the accent color to the light mode taskbar. It will be only enabled in dark mode. So it already works like this.

**Comment by dboun** [comment]
Hahaha sorry then, thank you!
