### ISSUE TITLE
Partially fires dark mode at 3:35pm every day, but only for Windows Explorer

### ISSUE THREAD

**Issue by kineticscreen** [Armin2208/Windows-Auto-Night-Mode#48]
**Describe the bug**
So pretty much every day, I'll be using the computer when on the dot at 3:35pm the Windows Explorer theme will change to night mode. Opening up Auto Dark Mode, it will think for a mnute, as the sunrise and sunset times display as the default 7am and 7pm, but then it will update the location information, and they will go back to being correctly set, at which point Windows Explorer will switch back to light mode.

**To Reproduce**
1. Occurs at precisely 3:35pm every day.
2. Set to Use Location Service

**Expected behavior**
This not to happen?

**Environment:**
 - OS Version: Windows 1903
 - Night-Mode Version 2.3
 - Has user admin rights? Yes
 - which antivirus software you use? Windows built in
 - what language is your Windows set to? English Australia

**Additional context**
At first I thought it might be something to do with a timezone issue, because it was happening 2 hours before sundown. But as the sunset time has shifted it keeps happening at 3:35pm.

![Annotation 2019-08-15 154337](https://user-images.githubusercontent.com/39250334/63075040-7e24dc80-bf73-11e9-9f40-458c6ca87e1a.jpg)

**Comment by Armin2208** [comment]
I have a theory: Go to Settings -> Account -> Sync Setting and deactive Settings synchronisation completly.

**Comment by Armin2208** [comment]
Maybe there is also an task left in task sheduler. 
Uncheck "Enable automatic theme switch" and then look at task sheduler if you still have an Auto Night Mode or Auto Dark Mode folder.

**Comment by kineticscreen** [comment]
Yup this fixed it. There were a couple of tasks in task scheduler :-)

<http://www.kineticscreen.com/>
www.kineticscreen.com
