### ISSUE TITLE
Auto dark mode doesnt work after update

### ISSUE THREAD

**Issue by irockdude554** [Armin2208/Windows-Auto-Night-Mode#49]
I just opened the app's GUI today and I noticed there was an app update so naturally I downloaded the update and updated the program however, after I updated the program I can no longer open it at all, I search for the program in my start menu and click on it, but nothing ever opens windows must be trying to load something because my cursor does the loading wheel but that's about it.

**Comment by Armin2208** [comment]
Looks like the App crashes at Startup. Because if you wouldn't have the newest Net-Framework-Version Windows shows a error message.

Look at the reliability monitor in the mantaince center of Windows. Is there an Auto Dark Mode crash listed?
Alternatively you can look in the Event Viewer.

And please tell me some more information. Which version did you used before? Which Windows version and edition do you use?

**Comment by irockdude554** [comment]
ahh! Sorry about that, i'm running windows 10 1903 64bit and the version I was running before I updated was 2.1.1. Looking in the reliablity monitor windows does show that auto dark mode is crashing [heres a screenshot of it](https://i.imgur.com/rd9Dw9A.png)

**Comment by Armin2208** [comment]
Perfect. Please click on view technical details and send me a screen shot of that.

**Comment by irockdude554** [comment]
any update on this?

**Comment by Armin2208** [comment]
Hello,

sorry for not responding to you. I will try to fix this bug in the next weeks. I'm a bit busy right now :/

**Comment by irockdude554** [comment]
ahh ok i figured that, just wanted to make sure you knew i sent the sscreenshot lol

**Comment by Armin2208** [comment]
On which language and region is your Windows set to?

**Comment by irockdude554** [comment]
US English

**Comment by Armin2208** [comment]
Sorry for waiting so long, but finally I'm working again on auto dark mode.
 please try this .exe and send a screenshot of the error message. thank you.

[AutoDarkMode_Setup.zip](https://github.com/Armin2208/Windows-Auto-Night-Mode/files/3730652/AutoDarkMode_Setup.zip)
