### ISSUE TITLE
Would be neat to see an option to pick different accent color for Dark and Light mode

### ISSUE THREAD

**Issue by TheGreySquare** [Armin2208/Windows-Auto-Night-Mode#51]
That's more of a nice addition. 
For example, more washed light pastel like accent like accent colors looks more distinct on Dark themes (Like in Material Design 2 (Android)) and vice versa. 
Hope it can be implemented.
P.S. App is working great on 1903.

**Comment by 19lmyers** [comment]
I literally just came here to suggest this (also inspired by Material.io's Dark Theme guidelines).

I'm not entirely sure if there's a way to do it, though. I haven't had any success changing the relevant registry keys manually myself.

**Comment by Armin2208** [comment]
Hey! Check out the new beta release and give me some feedback: [version 2.4 Beta](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases/tag/2.4)
