### ISSUE TITLE
[Feature request] Set specific files for specific monitors on switch

### ISSUE THREAD

**Issue by ShadowJonathan** [Armin2208/Windows-Auto-Night-Mode#53]
* Have the program be able to detect the current monitors in their position, and display them in the wallpaper dialog box
* Be able to set specific files for specific monitors when the program switches from light to dark theme and back

**Comment by Armin2208** [comment]
Hey! Check out the new beta release and give me some feedback: [version 2.4 Beta](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases/tag/2.4)

**Comment by ShadowJonathan** [comment]
I've mostly already found the feature I wanted from wallpaper engine, but it's nice that its been implemented in here :D
