### ISSUE TITLE
Submit as desktop bridge app to the Microsoft Store

### ISSUE THREAD

**Issue by yaichenbaum** [Armin2208/Windows-Auto-Night-Mode#54]
Would you consider submitting this application to the Microsoft Store? I would be happy to help you along that process if you are interested.

**Comment by yaichenbaum** [comment]
What was the issue? I have brought full desktop apps to the store before with the full trust capability, this application may be different but I would be happy to bring up the issue with some additional engineers and see if they can make this possible.

**Comment by Armin2208** [comment]
This would be awesome. How we can get into contact? Do you have Telegram?

**Comment by Armin2208** [comment]
Yes, I have.

**Comment by Armin2208** [comment]
Armin2208#5305

**Comment by Armin2208** [comment]
Duplicate of #17
