### ISSUE TITLE
still crashing on startup with the .exe you gave me in the previous thread.

### ISSUE THREAD

**Issue by irockdude554** [Armin2208/Windows-Auto-Night-Mode#55]
> 
> 
> Sorry for waiting so long, but finally I'm working again on auto dark mode.
> please try this .exe and send a screenshot of the error message. thank you.
> 
> [AutoDarkMode_Setup.zip](https://github.com/Armin2208/Windows-Auto-Night-Mode/files/3730652/AutoDarkMode_Setup.zip)

heres a screenshot showing the error with the new .exe you gave me [Link](https://i.imgur.com/LVtzGBO.png)

**Comment by Armin2208** [comment]
New EXE new Try :D
[AutoDarkMode_NoRelease.zip](https://github.com/Armin2208/Windows-Auto-Night-Mode/files/3746688/AutoDarkMode_NoRelease.zip)

**Comment by irockdude554** [comment]
thanks that works
