### ISSUE TITLE
Cursor Switching Support

### ISSUE THREAD

**Issue by KKire** [Armin2208/Windows-Auto-Night-Mode#57]
I'm requesting a feature that would also toggle cursor color if possible.
Further if possible, is to choose the black cursor from the new Windows 10 feature color selection (rgb screen) instead of the default clickable icon in System - Easy of Access since it's better.

**Comment by Armin2208** [comment]
Hey! Check out the new beta release and give me some feedback: [version 2.4 Beta](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases/tag/2.4)
