### ISSUE TITLE
[Feature request] Add automatic dark mode also in Microsoft edge

### ISSUE THREAD

**Issue by xGroSrv** [Armin2208/Windows-Auto-Night-Mode#6]
Since Microsoft system UI and explorer are not synchronized with Microsoft edge browser by default, when switching to dark mode, the browser remains light. it could be useful to add the option for include also the browser, and change both system and browser theme at the same time, every time. 

PS.
Thank you for your work, I really appreciate this tool!

**Comment by Armin2208** [comment]
Hello,

thanks for your feedback. I will add this feature to my App. But Microsoft Edge doesn't support Theme-Switching without restarting. Still better than nothing.
