### ISSUE TITLE
Give possibility to choose "light" and "dark" theme, like wallpapers.

### ISSUE THREAD

**Issue by rikipm** [Armin2208/Windows-Auto-Night-Mode#63]
I think it’s a good idea to let the user choose his custom "themes" for dark and light mode, like now he choose wallpapers. Reasons:

1. Inside theme settings user can choose not only "one picture" wallpaper, he can choose slideshow or solid color background (solves https://github.com/Armin2208/Windows-Auto-Night-Mode/issues/35). Also user can choose fit of image.

2. Inside theme settings user can choose accent color (solves https://github.com/Armin2208/Windows-Auto-Night-Mode/issues/51), lock screen, sounds scheme, mouse scheme (solves https://github.com/Armin2208/Windows-Auto-Night-Mode/issues/57), fonts and many other things for night mode.

We will give more functionality without the need to work on it, windows personalization do all work.

**Comment by Armin2208** [comment]
Thank you for creating the issue.
Working on it.

**Comment by Armin2208** [comment]
coming in the next update

**Comment by Armin2208** [comment]
Hey! Check out the new beta release and give me some feedback: [version 2.4 Beta](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases/tag/2.4)
