### ISSUE TITLE
Immediate application stop.

### ISSUE THREAD

**Issue by Polisson** [Armin2208/Windows-Auto-Night-Mode#64]
"A problem caused the program to stop working correctly. Please close the program."
![Schowek01](https://user-images.githubusercontent.com/24476033/68836531-e0989080-06ba-11ea-9bab-97b9b048cfb5.png)
That's it.
Windows 10 1607 2016 LTSB x64.

**Comment by Armin2208** [comment]
Fixed in version 2.3.1 but I need to hold the update due to a windows defender false positive.

**Comment by Armin2208** [comment]
new update is out now, please test it, thank you.
