### ISSUE TITLE
No switch if you change clock manually

### ISSUE THREAD

**Issue by samsong** [Armin2208/Windows-Auto-Night-Mode#70]
I had previously manually created a light/dark switch but forgot what setting I used.

When you manually change the computer clock from dark to light period the switch task does not run.

Can you update the task scheduler entry to cover this scenario?

**Comment by Spiritreader** [comment]
I understand the issue, but: 
Why would you change your system time constantly to a point where this becomes an issue?
If necessary you can manually switch it back using the app itself.
I'm not sure whether this is an intended scenario as the windows task scheduler functions as expected.

**Comment by samsong** [comment]
I don't change the date. Dual boot computer with Linux the clock gets reset everytime after you boot Linux and go back to windows. So this is a real issue normal experienced. I fixed it by updating the settings in the task scheduler and ticking some boxes to run every time, run at next opportunity. I can't remember exactly which but one of these settings was missing in the default schedule created by this app

**Comment by Armin2208** [comment]
OK I will check that
