### ISSUE TITLE
I try to install it ,but it doesn't work.

### ISSUE THREAD

**Issue by taylorsfan** [Armin2208/Windows-Auto-Night-Mode#71]
**Describe the bug**
i downloaded the lastest version and try to install it,but i failed,I reboot sometimes,but it can't work anyway.

**To Reproduce**
no reproduce.

**Screenshots**
i don't know how to make a gif.

**Environment:**
 - OS Version: Windows 1909
 - Night-Mode Version 2.3.1
 - Has user admin rights? yeas
 - which antivirus software you use? [huorong](https://huorong.cn)
 - what language is your Windows set to? zh-CN

**Additional context**

**Comment by taylorsfan** [comment]
I uninstall all antivirus softwares,but it doesn't work anyway

**Comment by Armin2208** [comment]
Press windows + Shift + S to make a Screenshot, and paste it with strg + v here into the GitHub comments while you focused the text box for answering.

**Comment by Spiritreader** [comment]
no update in more than 6 months, closing.
