### ISSUE TITLE
Office theme auto switching

### ISSUE THREAD

**Issue by udobehm** [Armin2208/Windows-Auto-Night-Mode#75]
Hi Armin,

thanks for your great program!

Could you also implement a feature to change the Office theme? I'm using Office 2019 and have set the black theme as default. However, I would like Office to change it's black and normal theme as well as the Windows theme switches by your app. Was nice if you could implement this!

Thank you and great holidays to you!
Udo

**Comment by Armin2208** [comment]
Thanks for your feedback.
duplicate of #24.

**Comment by udobehm** [comment]
Kann ja eigentlich auch auf deutsch mit dir reden :)

Denkst du, du bekommst das hin?? Wäre super, wenn Office auch mit on-board wäre...

**Comment by Armin2208** [comment]
Ich rede nicht mit dir auf Deutsch, weil das hier ein öffentlicher Raum ist und andere auch gerne mitlesen würden.

Ich bekäme es vielleicht hin, es ist aber sehr aufwendig und benötigt admin rechte. Es wünschen sich viele, ich schaue es mir mal an. Gib mir ein paar Monate.
