### ISSUE TITLE
[Suggestion] Change accent color when you change theme

### ISSUE THREAD

**Issue by MercuryXIII** [Armin2208/Windows-Auto-Night-Mode#78]
Some colors look great in light mode, whereas they look awful in dark mode. I am hoping we can get a feature in the future where the accent color can also change with the theme :)

Thank you Armin for all your hard work!

**Comment by Armin2208** [comment]
Hey! Check out the new beta release and give me some feedback: [version 2.4 Beta](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases/tag/2.4)

**Comment by MercuryXIII** [comment]
Works perfectly! Thanks!
