### ISSUE TITLE
version 3 frontend cannot launch links since switching to dnc 3.x

### ISSUE THREAD

**Issue by Spiritreader** [Armin2208/Windows-Auto-Night-Mode#83]
**Describe the bug**
Calling `Process.Start("urlstring");` causes a win32 exception with platform target dotnet core 3.x

**Expected behavior**
URL should open in the system default browser

**Environment:**
 - dotnet core 3.1

**Example of occurrence**
https://github.com/Armin2208/Windows-Auto-Night-Mode/blob/72a348a5595de97070dc1f905c81cc170e992f0d/AutoDarkModeApp/AboutWindow.xaml.cs#L121

**Additional context**
suggested fix: 
https://stackoverflow.com/a/53245993

**Comment by utkucanturkan** [comment]
The suggested fix has been applied actually I could not find any other approach and tested all starting process actions that take a URL as a parameter.

**Comment by Spiritreader** [comment]
Thanks a lot!
