### ISSUE TITLE
[Suggestion] Silent install with preconfigured options

### ISSUE THREAD

**Issue by Fanman03** [Armin2208/Windows-Auto-Night-Mode#88]
I would like to be able to deploy this to all of the machines on my Active Directory (AD) domain without having to manually install it on each one. Would you consider adding a CLI option to the installer that allows this?
Maybe something like `AutoDarkMode_Setup.exe -silent -config configfile.json`

Thanks for the awesome app.

**Comment by NicTanghe** [comment]
yeah and sinse you'd be doing that maybe also ad a chocolatey repo :D

**Comment by Armin2208** [comment]
Hello Guys.
The Installer supports silent installing with the argument /verysilent.
You can't include a configfile, but I think the AppData-Path is perfect.
Thanks for your interest. If you still have questions feel free to ask me :)

**Comment by Armin2208** [comment]
> yeah and sinse you'd be doing that maybe also ad a chocolatey repo :D

Someone made a chocolatey repo and maintains it. Don't know who is this, but he seems like to always upate the tool. Is this a okay repo?
https://chocolatey.org/packages/auto-dark-mode
