### ISSUE TITLE
Windows-Auto-Night-Mode does not work other than specfied time!

### ISSUE THREAD

**Issue by matsuda0707** [Armin2208/Windows-Auto-Night-Mode#9]
**Describe the bug**
When the system is powered on after the specified light time, it does not change the night mode!
Windows-Auto-Night-Mode only set the light and dark mode time on the task scheduler, and so if I power on PC after the specified light time, the dark mode remains unchanged.

**Comment by Armin2208** [comment]
Hello,

Thanks for reporting this bug. I'll try to fix it. 

Thank you!

**Comment by matsuda0707** [comment]
I checked the new beta version, and also found that the mode change after the specified time (ex. 7:30 startup at 7:00 specified) did not work as the previous version.
I checked the settings of task scheduler, but the settings are correct. 
Does everyone work properly inthis case (startup other than the specified time range?

**Comment by Armin2208** [comment]
Hello!

Auto-Night Mode 2.0 is now final and released. I fixed the mentioned bug of you. Please check out the newest version and give me feedback about your experience now.

Thank you!

[Click here to download the new version](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases)

**Comment by matsuda0707** [comment]
Thanks for new version.
I installed and tested, but the result was the same.
This morning I got up around 6:30, and found your mail.
So I installed it and set to 7 to 19 Light mode (no Local service).

Then I confirmed the Night mode and shutdown the system, and after 7:00 I powered PC, but the mode was still Night mode.

**Comment by Armin2208** [comment]
It can take 5 minutes before the theme switches. Could you please monitor the behavior of the app a bit more? Would be nice of you!

**Comment by matsuda0707** [comment]
I tested the switch of mode, and I set to Night mode, and restarted the system after the specified Light mode time.
But it still dark mode even after 10 minutes. Something is wrong?

**Comment by matsuda0707** [comment]
I monitored 2.0 and it works normally.
I propose to create Auto-Night Mode shortcut with /switch parameter (I did so) to change mode immediatelly after startup.

**Comment by Armin2208** [comment]
This is how 2.0 works now. I hope your issues are now solved :)

**Comment by matsuda0707** [comment]
I closed this post!
