### ISSUE TITLE
Taskbar date and time display problems in windows10

### ISSUE THREAD

**Issue by liuqi0270** [Armin2208/Windows-Auto-Night-Mode#91]
**Describe the bug**
In Windows 10 light mode, the time and date color in the taskbar is black and cannot be seen clearly. It was restored after adjustment, but the word turned black again when the software was started. Is this a bug?

thanks

**Environment:**
 - OS Version: [ Windows 10.0.19041.153]
 - Night-Mode Version [2.3.1]
 - Has user admin rights?
 - which antivirus software you use?
 - what language is your Windows set to?

**Additional context**

**Comment by Armin2208** [comment]
do you use a battery powered device?

**Comment by liuqi0270** [comment]
> do you use a battery powered device?


Thank you.  I am not a battery powered device

**Comment by Spiritreader** [comment]
possibly also related to #76 

Will need to retest in v3 with a custom offset that has been introduced in d280e1053824b95436f0fe593cef6470bc534b79 once released to public

**Comment by Armin2208** [comment]
Do you have enabled the option use Accent Color for Taskbar?

**Comment by liuqi0270** [comment]
感谢回复，我选择了windows颜色，任务栏勾选。我尝试了最新版本，仍然有这个问题存在。在亮色模式下任务栏的时间就会变成黑字。需要手动切换主题可以恢复。

Thanks for the reply, I chose the windows color and ticked the task bar. I tried the latest version and still have this problem. In bright mode, the time in the taskbar will become black. Need to manually switch the theme can be restored.

**Comment by liuqi0270** [comment]
> possibly also related to #76
> 
> Will need to retest in v3 with a custom offset (and hopefully the fix for this issue) that has been introduced in [d280e10](https://github.com/Armin2208/Windows-Auto-Night-Mode/commit/d280e1053824b95436f0fe593cef6470bc534b79) once released to public
> 
> Update: This will be fixed in 3.0 because the theme switching mechanism has changed.
> For 2.4 classic mode further mitigation possibilities will need to be explored.

thanks

**Comment by Spiritreader** [comment]
Setting a long enough tunable delay in the Auto Dark Mode settings should fix this.

The fix is present in both v3 and also vX.
