### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by carvaofficial** [Armin2208/Windows-Auto-Night-Mode#92]
Hi, I'm Angel and I'm a programmer too. I saw that your software don't have a translation to Spanish. I'm from Spain so I can help you to translate the strings. If you agree and it's okay, I can help you

**Comment by Armin2208** [comment]
thanks for the offer. As you see I had a translation already on my pc. I commited at now because I am back working on the software. If you have some things to improve, fix, feel free to commit :)
