### ISSUE TITLE
你们可以尝试只修改颜色中的默认应用模式，亮和暗处于自动状态就可以。这个软件现在会自动改变win10的默认模式。而这个软件切换主要目的是自动开启亮暗模式，而不是切换主题。

### ISSUE THREAD

**Issue by GMN-git** [Armin2208/Windows-Auto-Night-Mode#94]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - OS Version: [e.g. Windows 1803]
 - Night-Mode Version [e.g. 1.0]
 - Has user admin rights?
 - which antivirus software you use?
 - what language is your Windows set to?

**Additional context**

**Comment by GMN-git** [comment]
你们可以尝试只修改颜色中的默认应用模式，亮和暗处于自动状态就可以。这个软件现在会自动改变win10的默认模式。而这个软件切换主要目的是自动开启亮暗模式，而不是切换主题。

**Comment by GMN-git** [comment]
希望可以后期修改留意以下，谢谢！

**Comment by Armin2208** [comment]
google translator can't translate this lol

**Comment by URenko** [comment]
What he means is to only modify the theme of the system, not the app.
 But it seems that this program already provided this function.

**Comment by Armin2208** [comment]
@URenko thanks for the info!
