### ISSUE TITLE
Task Scheduler: Theme Switch Delay

### ISSUE THREAD

**Issue by ncodee** [Armin2208/Windows-Auto-Night-Mode#96]
**Describe the bug**
Theme does not switch instantly or within a few seconds upon login using Task Scheduler implementation

**To Reproduce**
1) Login Windows Account
2) Theme takes a while to switch

**Expected behavior**
Switch theme automatically (near instantly) upon login

**Screenshots**

**Environment:**
 - OS Version: - 2004
 - Night-Mode Version - 2.3.1
 - Has user admin rights? - Yes
 - which antivirus software you use? - Microsoft Defender + Malwarebytes
 - what language is your Windows set to? - English

**Additional context**
I'm aware that it's unlikely possible for the theme to switch instantly, but it takes a couple of seconds than expected to switch themes, even with Task Scheduler implentation. I'm not sure if this is a limitation, or something else?

**Comment by Armin2208** [comment]
so you have a multi user configuration and your pc is always on. You switch the user and then you expect Auto Dark Mode to instantly switch the theme. And you never logout of your user account?

**Comment by JesFEREM** [comment]
Windows has a built in startup delay that's for the most part hard to bypass. 
I know that WinDynamicDesktop has this, but i don't know how they managed to bypass it because I'm not a programmer. Auto-night-mode starts via the startup programs in windows, so it's unavoidable that it'd take a few seconds to start up and do it's job.

**Comment by ncodee** [comment]
> so you have a multi user configuration and your pc is always on. You switch the user and then you expect Auto Dark Mode to instantly switch the theme. And you never logout of your user account?

I'm not sure how you came to that assumption. I have a single user setup, and the PC is never left on. What I am saying is, upon login/boot/reboot etc, there is a slight delay on the Task scheduler upon startup. it takes around a good 10-15 seconds to switch theme.

**Comment by Armin2208** [comment]
Okay thanks! Misunderstood that
